<?php

namespace Drupal\mini_wiki\Routing;

use Drupal\Core\Routing\RouteSubscriberBase;
use Symfony\Component\Routing\RouteCollection;

/**
 * Listens to the dynamic route events.
 */
class RouteSubscriber extends RouteSubscriberBase {

  /**
   * {@inheritdoc}
   */
  public function alterRoutes(RouteCollection $collection) {
    // Replace the content from mini_wiki_page.version_history route with content
    // generated by revisionOverview method from MiniWikiRevisionController class.
    $route = $collection->get('entity.mini_wiki_page.version_history');
    if ($route) {
      $route->addDefaults(
        [
          '_controller' => '\Drupal\mini_wiki\Controller\MiniWikiRevisionController::revisionOverview',
        ],
      );
    }
  }

}
