<?php declare(strict_types = 1);

/**
 * Developed by Natiboo <info@natiboo.es>
 *
 * @license https://www.gnu.org/licenses/agpl-3.0.en.html GNU AFFERO GENERAL PUBLIC LICENSE
 * @link http://natiboo.es
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\labdoo_common\Event\InvalidateCacheTagsEvent;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function labdoo_dootronics_theme() {

  return [
    'dootronics_chart_block_block' => [
      'variables' => [
        'status_info' => NULL,
      ],
      'template' => 'block--dootronics-chart-block',
    ],
    'dootronics_actions_block_block' => [
      'variables' => [
        'edit_link' => '',
        'revisions_link' => '',
        'clone_link' => '',
        'print_labels_link' => '',
        'follow_link' => '',
        'unfollow_link' => '',
        'pick_me_up_status' => '',
        'pick_me_up_link' => '',
        'next_link' => '',
        'previous_link' => '',
      ],
      'template' => 'block--dootronics-actions-block',
    ],
    'dootronics_label' => [
      'variables' => [
        'dootronics_collection' => NULL,
      ],
      'template' => 'dootronics-label',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function labdoo_dootronics_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (
    $form_id === 'views_exposed_form' &&
    isset($form['#id'])
    && $form['#id'] === 'views-exposed-form-dootronics-dashboard-page-1'
  ) {
    /** @var \Drupal\labdoo_common\Service\Repository\CommonRepository $commonRepository */
    $commonRepository = \Drupal::service('labdoo_common.repository.common');
    $activeCountries = $commonRepository->getActiveCountries('dootronic');
    $allCountries = $form['field_country_value']['#options'];
    $selectedCountries = array_intersect_key(
      $allCountries,
      array_flip($activeCountries)
    );
    $selectedCountries = array_merge(
      ['All' => t('- Any -')],
      $selectedCountries
    );
    $form['field_country_value']['#options'] = $selectedCountries;
  }
}

/**
 * Implements hook_entity_presave().
 */
function labdoo_dootronics_entity_presave(EntityInterface $entity) {
  if ($entity->bundle() !== 'dootronic') {
    return;
  }

  // If this is a new dootronic node, set its ID using the sequence manager
  if ($entity->isNew()) {
    /** @var \Drupal\labdoo_dootronics\Service\SequenceManagerInterface $sequenceManager */
    $sequenceManager = \Drupal::service('labdoo_dootronics.sequence_manager');
    $nid = $sequenceManager->get();
    $entity->set('nid', $nid);
  }

  /** @var \Drupal\labdoo_dootronics\Service\Compute\DootronicComputeInterface $dootronicCompute */
  $dootronicCompute = \Drupal::service('labdoo_dootronics.compute');
  $dootronicCompute->setDootronicTitle($entity);
  $dootronicCompute->computeWattHours($entity);
}

/**
 * Implements hook_entity_insert().
 */
function labdoo_dootronics_entity_insert(EntityInterface $entity) {
  __labdoo_dootronics_recalculate($entity);
}

/**
 * Implements hook_entity_update().
 */
function labdoo_dootronics_entity_update(EntityInterface $entity) {
  __labdoo_dootronics_recalculate($entity);

  if ($entity->bundle() === 'dootronic') {
    /** @var \Drupal\labdoo_dootronics\Service\Compute\DootronicComputeInterface $dootronicCompute */
    $dootronicCompute = \Drupal::service('labdoo_dootronics.compute');
    $dootronicCompute->computeRelatedDootrips($entity);
  }
}

/**
 * Implements hook_entity_delete().
 */
function labdoo_dootronics_entity_delete(EntityInterface $entity) {
  __labdoo_dootronics_recalculate($entity);
}

function __labdoo_dootronics_recalculate(EntityInterface $entity): void {
  if ($entity->bundle() !== 'dootronic') {
    return;
  }

  /** @var \Drupal\labdoo_dootronics\Service\Compute\DootronicComputeInterface $dootronicCompute */
  $dootronicCompute = \Drupal::service('labdoo_dootronics.compute');
  $dootronicCompute->computeEdooVillageData($entity);
  $dootronicCompute->computeHubData($entity);
  __labdoo_dootronics_clear_cachetag($entity);
}

/**
 * Implements hook_views_query_alter().
 */
function labdoo_dootronics_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'dootronics_dashboard' && $view->current_display == 'page_1') {
    $user_id = \Drupal::request()->query->get('u');
    $mine = \Drupal::request()->query->get('mine');

    if (!empty($user_id) && is_numeric($user_id)) {
      $query->addWhere('AND', 'node_field_data.uid', $user_id, '=');
    }
    elseif (!empty($mine) && (int) $mine === 1) {
      $query->addWhere('AND', 'node_field_data.uid', \Drupal::currentUser()->id(), '=');
    }
  }
}

/**
 * Invalidate the node type cache tag.
 *
 * @return void
 */
function __labdoo_dootronics_clear_cachetag(EntityInterface $entity) {
  $dootronicTag = sprintf(
    'dootronic:%d:%d',
    $entity->id(),
    \Drupal::currentUser()->id()
  );
  $tags = [
    'dootronics_chart',
    $dootronicTag,
  ];
  $event = new InvalidateCacheTagsEvent();
  $event->setCacheTags($tags);

  /** @var \Symfony\Component\EventDispatcher\EventDispatcherInterface $eventDispatcher */
  $eventDispatcher = \Drupal::service('event_dispatcher');
  $eventDispatcher->dispatch($event, InvalidateCacheTagsEvent::EVENT_NAME);
}
