<?php

declare(strict_types=1);

/**
 * Developed by Natiboo <info@natiboo.es>
 *
 * @license https://www.gnu.org/licenses/agpl-3.0.en.html GNU AFFERO GENERAL PUBLIC LICENSE
 * @link http://natiboo.es
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_form_alter().
 */
function labdoo_wiki_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form['#id'] === 'views-exposed-form-wiki-page-2') {
    $current_path = \Drupal::service('path.current')->getPath();
    if ($current_path === '/wiki' && isset($form['langcode_1'])) {
        $form['langcode_1']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_views_query_alter().
 */
function labdoo_wiki_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'wiki' && $view->current_display == 'page_1') {
    $user_id = \Drupal::request()->query->get('u');
    $mine = \Drupal::request()->query->get('mine');

    if (!empty($user_id) && is_numeric($user_id)) {
      $query->addWhere('AND', 'mini_wiki_page_field_data.uid', $user_id, '=');
    }
    elseif (!empty($mine) && (int) $mine === 1) {
      $query->addWhere('AND', 'mini_wiki_page_field_data.uid', \Drupal::currentUser()->id(), '=');
    }
  }
}

/**
 * Implements hook_preprocess_menu().
 */
function labdoo_wiki_preprocess_menu(&$variables): void {
  if (!\Drupal::currentUser()->isAnonymous()) {
    return;
  }

  foreach ($variables['items'] as $key => $item) {
    foreach ($item['below'] as $subkey => $subitem) {
      if (!isset($subitem['url']) || !$subitem['url'] instanceof Url) {
        continue;
      }

      if (
        $subitem['title'] === 'My wiki articles'
        && $subitem['url']->getRouteName() === 'view.wiki.page_1'
      ) {
        unset($variables['items'][$key]['below'][$subkey]);
      }
    }
  }
}

/**
 * Implements hook_link_checker_supported_entity_types().
 */
function labdoo_wiki_link_checker_supported_entity_types() {
  return [
    'wiki_page' => [
      'enabled' => TRUE,
    ],
  ];
}

/**
 * Implements hook_link_checker_scan_entity_fields().
 */
function labdoo_wiki_link_checker_scan_entity_fields($entity_type_id) {
  if ($entity_type_id === 'wiki_page') {
    return [
      'body',
      'parent',
    ];
  }
}

/**
 * Implements hook_link_checker_entity_access().
 */
function labdoo_wiki_link_checker_entity_access($entity) {
  if ($entity->getEntityTypeId() === 'wiki_page') {
    return $entity->access('update');
  }
}
