<?php declare(strict_types = 1);

/**
 * Developed by Natiboo <info@natiboo.es>
 *
 * @license https://www.gnu.org/licenses/agpl-3.0.en.html GNU AFFERO GENERAL PUBLIC LICENSE
 * @link http://natiboo.es
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\labdoo_common\Event\InvalidateCacheTagsEvent;

function labdoo_statistics_theme() {
  return [
    'statistics_block_block' => [
      'variables' => [
        'dootronics_tagged' => 0,
        'dootronics_delivered' => 0,
        'edoovillages' => 0,
        'students' => 0,
        'hubs' => 0,
        'co2' => 0,
        'countries' => 0,
        'dootronics_url' => '',
        'edoovillages_url' => '',
        'hubs_url' => '',
      ],
      'template' => 'block--statistics-block',
    ],
  ];
}

