<?php declare(strict_types = 1);

/**
 * Developed by Natiboo <info@natiboo.es>
 *
 * @license https://www.gnu.org/licenses/agpl-3.0.en.html GNU AFFERO GENERAL PUBLIC LICENSE
 * @link http://natiboo.es
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\labdoo_common\Event\InvalidateCacheTagsEvent;

function labdoo_statistics_theme() {
  return [
    'statistics_block_block' => [
      'variables' => [
        'dootronics_tagged' => 0,
        'dootronics_delivered' => 0,
        'edoovillages' => 0,
        'students' => 0,
        'hubs' => 0,
        'co2' => 0,
        'countries' => 0,
        'dootronics_url' => '',
        'edoovillages_url' => '',
        'hubs_url' => '',
      ],
      'template' => 'block--statistics-block',
    ],
    'labdoo_advanced_statistics' => [
      'variables' => [
        'evolution_data' => NULL,
        'status_data' => NULL,
        'country_data' => NULL,
        'edoovillage_evolution' => NULL,
        'hub_status_data' => NULL,
        'hub_evolution' => NULL,
        'hubs_by_country' => NULL,
        'top_hubs_activity' => NULL,
        'dootrip_km_data' => NULL,
        'task_type_data' => NULL,
        'priority_data' => NULL,
        'task_status_data' => NULL,
        'node_evolution_data' => NULL,
        'team_activity_data' => NULL,
        'content_type_data' => NULL,
        'comment_evolution_data' => NULL,
        'top_dootronic_contributors' => NULL,
        'top_commenters' => NULL,
        'tasks_by_team_data' => NULL,
        'wiki_stats' => NULL,
        'platform_uptime' => NULL,
        'dootronic_device_data' => NULL,
        'dootronic_cpu_data' => NULL,
        'laptops_per_edoovillage' => NULL,
        'laptops_per_student' => NULL,
      ],
      'template' => 'advanced-statistics',
    ],
  ];
}

/**
 * Implements hook_entity_insert().
 */
function labdoo_statistics_entity_insert(EntityInterface $entity) {
  if (
    $entity->bundle() !== 'dootronic'
    && $entity->bundle() !== 'edoovillage'
    && $entity->bundle() !== 'hub'
    && $entity->bundle() !== 'dootrip'
  ) {
    return;
  }

  __labdoo_statistics_clear_cachetag($entity);
}

/**
 * Implements hook_entity_delete().
 */
function labdoo_statistics_entity_delete(EntityInterface $entity) {
  if (
    $entity->bundle() !== 'dootronic'
    && $entity->bundle() !== 'edoovillage'
    && $entity->bundle() !== 'hub'
    && $entity->bundle() !== 'dootrip'
  ) {
    return;
  }

  __labdoo_statistics_clear_cachetag($entity);
}

/**
 * Invalidate the node type cache tag.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The entity.
 *
 * @return void
 */
function __labdoo_statistics_clear_cachetag(EntityInterface $entity): void {
  $tag = sprintf('node:%s', $entity->bundle());
  $event = new InvalidateCacheTagsEvent();
  $event->setCacheTags([$tag]);

  /** @var \Symfony\Component\EventDispatcher\EventDispatcherInterface $eventDispatcher */
  $eventDispatcher = \Drupal::service('event_dispatcher');
  $eventDispatcher->dispatch($event, InvalidateCacheTagsEvent::EVENT_NAME);
}
