<?php

declare(strict_types=1);

/**
 * Developed by Natiboo <info@natiboo.es>
 *
 * @license https://www.gnu.org/licenses/agpl-3.0.en.html GNU AFFERO GENERAL PUBLIC LICENSE
 * @link http://natiboo.es
 */

/**
 * Implements hook_entity_type_build().
 */
function labdoo_privileges_entity_type_build(array $entity_types) {
  if (isset($entity_types['node'])) {
    $entity_types['node']->setHandlerClass('access', 'Drupal\labdoo_privileges\Access\LabdooNodeAccessControlHandler');
  }
}
