<?php declare(strict_types=1);

/**
 * Developed by Natiboo <info@natiboo.es>
 *
 * @license https://www.gnu.org/licenses/agpl-3.0.en.html GNU AFFERO GENERAL PUBLIC LICENSE
 * @link http://natiboo.es
 */

use Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException;
use Drupal\Component\Plugin\Exception\PluginNotFoundException;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\labdoo_common\Event\InvalidateCacheTagsEvent;
use Drupal\node\NodeInterface;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function labdoo_hub_theme() {

  return [
    'hub_chart_block_block' => [
      'variables' => [
        'needed' => NULL,
        'delivered' => NULL,
        'in_transit' => NULL,
        'remaining' => NULL,
      ],
      'template' => 'block--hub-chart-block',
    ],
    'hub_actions_block_block' => [
      'variables' => [
        'edit_link' => '',
        'photo_album_link' => '',
        'story_link' => '',
        'write_story_link' => '',
        'revisions_link' => '',
        'clone_link' => '',
        'next_link' => '',
        'previous_link' => '',
        'semaphore' => NULL,
        'dropping' => '',
        'sanitation' => '',
        'dootronics_link' => '',
        'dootrips_link' => '',
      ],
      'template' => 'block--hub-actions-block',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function labdoo_hub_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (
    $form_id === 'views_exposed_form' &&
    isset($form['#id'])
    && $form['#id'] === 'views-exposed-form-hubs-dashboard-page-1'
  ) {
    labdoo_common_set_active_countries($form, 'hub');
  }
}

/**
 * Implements hook_preprocess_HOOK() for node templates.
 */
function labdoo_hub_preprocess_node(&$variables) {
  $entity = $variables['node'];
  if (!$entity instanceof NodeInterface || $entity->bundle() !== 'hub') {
    return;
  }

  $variables['branches'] = _labdoo_hub_get_branches_list($entity->id());
}

/**
 * Implements hook_entity_insert().
 */
function labdoo_hub_entity_insert(EntityInterface $entity) {
  __labdoo_hub_clear_cachetag($entity);

  if ($entity->bundle() === 'hub') {
    labdoo_gallery_create_or_update($entity);
  }
}

/**
 * Implements hook_entity_update().
 */
function labdoo_hub_entity_update(EntityInterface $entity) {
  __labdoo_hub_clear_cachetag($entity);

  if ($entity->bundle() === 'hub') {
    labdoo_gallery_create_or_update($entity);
  }
}

/**
 * Implements hook_entity_delete().
 */
function labdoo_hub_entity_delete(EntityInterface $entity) {
  __labdoo_hub_clear_cachetag($entity);
}

/**
 * Implements hook_page_attachments().
 */
function labdoo_hub_page_attachments(array &$attachments) {
  $entity = \Drupal::routeMatch()->getParameter('node');
  if (!$entity instanceof NodeInterface || $entity->bundle() !== 'hub') {
    return;
  }

  $branches = _labdoo_hub_get_branches_list($entity->id());
  $hubLocations = _labdoo_hub_get_hub_locations($entity);
  $allLocations = _labdoo_hub_get_branches_list_locations($branches);
  $allLocations = array_merge($allLocations, $hubLocations);
  $data = [
    'branches' => $branches,
    'locations' => $allLocations,
  ];
  $attachments['#attached']['drupalSettings']['labdoo_hub']['data'] = $data;
  $attachments['#attached']['library'][] = 'labdoo_hub/gmaps';
}

/**
 * Implements hook_views_query_alter().
 */
function labdoo_hub_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'hubs_dashboard') {
    $user_id = \Drupal::request()->query->get('u');
    $mine = \Drupal::request()->query->get('mine');

    if (!empty($user_id) && is_numeric($user_id)) {
      $query->addWhere('AND', 'node_field_data.uid', $user_id, '=');
    }
    elseif (!empty($mine) && (int) $mine === 1) {
      $query->addWhere('AND', 'node_field_data.uid', \Drupal::currentUser()->id(), '=');
    }
  }
}

/**
 * Invalidate the node type cache tag.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The entity to invalidate the cache tag for.
 */
function __labdoo_hub_clear_cachetag(EntityInterface $entity): void {
  $dootronicTag = sprintf(
    'hub:%d:%d',
    $entity->id(),
    \Drupal::currentUser()->id()
  );
  $tags = [
    'hub_chart',
    $dootronicTag,
  ];
  $event = new InvalidateCacheTagsEvent();
  $event->setCacheTags($tags);

  /** @var \Symfony\Component\EventDispatcher\EventDispatcherInterface $eventDispatcher */
  $eventDispatcher = \Drupal::service('event_dispatcher');
  $eventDispatcher->dispatch($event, InvalidateCacheTagsEvent::EVENT_NAME);
}

/**
 * Retrieves the branches list of a given hub.
 *
 * @param mixed $hubId
 *   The hub ID.
 *
 * @param $levelsLeft
 *   The levels left to search.
 *   Default: 3.
 *
 * @return array
 *   The branches list.
 */
function _labdoo_hub_get_branches_list($hubId, int $levelsLeft = 3): array {
  if (!is_numeric($hubId)) {
    return [];
  }

  $hubId = (int) $hubId;
  --$levelsLeft;

  try {
    $result = \Drupal::entityTypeManager()
      ->getStorage('node')
      ->loadByProperties([
        'field_parent_hub' => $hubId,
      ]);
  }
  catch (InvalidPluginDefinitionException | PluginNotFoundException $e) {
    \Drupal::logger('labdoo_hub')->error($e->getMessage());

    return [];
  }

  // Find also all hub branches from this hub recursively (for all sublevels).
  $branchList = [];
  foreach ($result as $item) {
    if ($levelsLeft) {
      $branchListSubLevels = _labdoo_hub_get_branches_list($item->id(), $levelsLeft);
      $branchList = array_merge($branchList, $branchListSubLevels);
    }
    $branchList[] = $item;
  }

  return $branchList;
}

/**
 * Retrieves the locations of all the branches of a hub.
 *
 * @param array $branchList
 *   The branches list.
 *
 * @return array
 *   An array with the branches enriched with their locations.
 */
function _labdoo_hub_get_branches_list_locations(array $branchList): array {
  $allLocations = [];

  foreach ($branchList as $hub) {
    $hubLocations = _labdoo_hub_get_hub_locations($hub);
    $allLocations = array_merge($allLocations, $hubLocations);
  }

  return $allLocations;
}

/**
 * Retrieves the locations of a hub.
 *
 * @param \Drupal\Core\Entity\EntityInterface $hub
 *   The hub entity.
 *
 * @return array
 *   An array with the hub locations.
 */
function _labdoo_hub_get_hub_locations(EntityInterface $hub): array {
  $hubLocations = $hub->get('field_locations')->getValue();
  $locations = [];

  foreach ($hubLocations as $hubLocation) {
    if (!isset($hubLocation['lat']) || !isset($hubLocation['lon'])) {
      continue;
    }

    $locations[] = [
      'title' => $hub->label(),
      'coords' => [
        'lat' => $hubLocation['lat'],
        'lng' => $hubLocation['lon'],
      ],
    ];
  }

  return $locations;
}
