<?php declare(strict_types=1);

/**
 * Developed by Natiboo <info@natiboo.es>
 *
 * @license https://www.gnu.org/licenses/agpl-3.0.en.html GNU AFFERO GENERAL PUBLIC LICENSE
 * @link http://natiboo.es
 */

use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_theme().
 */
function labdoo_story_theme() {
  return [
    'story_actions_block_block' => [
      'variables' => [
        'edit_link' => '',
        'next_link' => '',
        'previous_link' => '',
        'parent_link' => '',
        'parent_title' => '',
        'parent_type' => '',
        'created' => '',
        'updated' => '',
      ],
      'template' => 'block--story-actions-block',
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function labdoo_story_form_node_labdoo_story_form_alter(
  &$form,
  FormStateInterface $form_state,
  $form_id
) {
  /** @var \Drupal\labdoo_story\Service\ParentEntityManager $parentEntityManager */
  $parentEntityManager = \Drupal::service('labdoo_story.parent_entity_manager');
  try {
    $parentEntity = $parentEntityManager->resolveParentEntity();
    $form['field_parent']['widget'][0]['target_id']['#default_value'] = $parentEntity;
    $form['field_parent']['widget'][0]['target_id']['#attributes']['readonly'] = 'readonly';
  }
  catch (Exception $e) {
    $response = new RedirectResponse('/');
    $response->send();
    exit;
  }
}
