# Schema for the configuration files of the Registration module.

registration.type.*:
  type: config_entity
  label: 'Registration type settings'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    workflow:
      type: string
      label: 'Workflow'
    defaultState:
      type: string
      label: 'Default state'
    heldExpireTime:
      type: integer
      label: 'Hold expiration hours'
    heldExpireState:
      type: string
      label: 'Hold expiration state'

registration.settings:
  type: config_object
  label: 'Registration settings'
  mapping:
    set_and_forget:
      type: boolean
      label: 'Set and forget mode'
    hide_filter:
      type: integer
      label: 'Manage Registrations filter threshold'
    queue_notifications:
      type: integer
      label: 'Queue notifications threshold'

field.formatter.settings.registration_host_entity:
  type: mapping
  label: 'Host entity display format settings'
  mapping:
    link:
      type: boolean
      label: 'Link'

field.widget.settings.registration_type:
  type: mapping
  label: 'Registration type widget settings'
  mapping:
    hide_register_tab:
      type: boolean
      label: 'Hide Register Tab'

field.value.registration:
  type: mapping
  label: 'Default value'
  mapping:
    registration_type:
      type: string
      label: 'Registration type'
    registration_settings:
      type: string
      form_element_class: \Drupal\registration\FormElement\RegistrationSettings
      label: 'Registration settings'

registration.state:
  type: workflows.state
  mapping:
    active:
      type: boolean
      label: 'Active'
    held:
      type: boolean
      label: 'Held'
    show_on_form:
      type: boolean
      label: 'Show on form'
    description:
      type: string
      label: 'Description'

workflow.type_settings.registration:
  type: mapping
  mapping:
    states:
      type: sequence
      label: 'Registration states'
      orderby: key
      sequence:
        type: registration.state
        label: 'States'
    transitions:
      type: sequence
      orderby: key
      sequence:
        type: workflows.transition
        label: 'Transitions'
    default_registration_state:
      type: string
      label: 'Default registration state'
