<?php

/**
 * Developed by Natiboo <info@natiboo.es>
 *
 * @license https://www.gnu.org/licenses/agpl-3.0.en.html GNU AFFERO GENERAL PUBLIC LICENSE
 * @link http://natiboo.es
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function labdoo_legal_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.labdoo_legal':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Labdoo Legal module provides functionality for managing Terms and Conditions across multiple languages.') . '</p>';
      return $output;
  }
}
